"use client";

import { useState, useCallback, useEffect, lazy, Suspense } from "react";
import {
  TrendingUp,
  Brain,
  Shield,
  BarChart3,
  Zap,
  Globe,
  FileDown,
  FileSpreadsheet,
  Share2,
  Check,
  Search,
  Loader2,
  Building2,
  Home as HomeIcon,
  Hotel,
  Sparkles,
  Info,
} from "lucide-react";
import { SearchBar } from "@/components/SearchBar";
import { PropertyDetails } from "@/components/PropertyDetails";
import { MapView } from "@/components/MapView";
import { RentGauge } from "@/components/RentGauge";
import { MarketTrends } from "@/components/MarketTrends";
import { Comparables } from "@/components/Comparables";
import { NeighborhoodStats } from "@/components/NeighborhoodStats";
import { CompareProperties } from "@/components/CompareProperties";
import { ErrorBoundary } from "@/components/ui/ErrorBoundary";
import { ShimmerLoader } from "@/components/ui/ShimmerLoader";
import { PanelCard } from "@/components/ui/PanelCard";
import { useStaggeredLoad } from "@/hooks/useStaggeredLoad";

// Lazy load below-fold panels
const IntelligenceFeed = lazy(() => import("@/components/IntelligenceFeed").then(m => ({ default: m.IntelligenceFeed })));
const InvestmentBrief = lazy(() => import("@/components/InvestmentBrief").then(m => ({ default: m.InvestmentBrief })));
const CashFlowCalculator = lazy(() => import("@/components/CashFlowCalculator").then(m => ({ default: m.CashFlowCalculator })));
const RiskScore = lazy(() => import("@/components/RiskScore").then(m => ({ default: m.RiskScore })));
import {
  mockProperty,
  mockComparables,
  mockRentEstimate,
  mockMarketData,
  mockNeighborhood,
  mockIntelItems,
  mockInvestmentBrief,
} from "@/lib/mockData";

export default function Home() {
  const [hasSearched, setHasSearched] = useState(false);
  const [propertyType, setPropertyType] = useState<"condo" | "multi-family" | "single-family">("condo");
  const { visiblePanels, loadedPanels, sourceCount, currentSourceName, isSearching, isInitializing, triggerLoad, resetSearch } =
    useStaggeredLoad(11);

  const [copied, setCopied] = useState(false);
  const [showHowItWorks, setShowHowItWorks] = useState(false);

  const [analysisTimestamp, setAnalysisTimestamp] = useState("");

  // Avoid hydration mismatch: only compute timestamp on client
  useEffect(() => {
    setAnalysisTimestamp(
      new Date().toLocaleString("en-US", {
        month: "long",
        day: "numeric",
        year: "numeric",
        hour: "numeric",
        minute: "2-digit",
        hour12: true,
      })
    );
  }, [hasSearched]);

  const handleSearch = useCallback(
    (_address: string) => {
      setHasSearched(true);
      triggerLoad();
      window.scrollTo({ top: 0, behavior: "smooth" });
    },
    [triggerLoad]
  );

  const handleNewAnalysis = useCallback(() => {
    setHasSearched(false);
    resetSearch();
  }, [resetSearch]);

  const handleShare = useCallback(() => {
    navigator.clipboard.writeText(
      `PropVision Analysis: 350 Fifth Avenue, New York, NY 10118\n\nEstimated Value: $1,275,000\nRent Estimate: $4,500/mo\nCap Rate: 4.24%\nRisk Rating: LOW-MODERATE\n\nGenerated by PropVision AI — propvision.ai`
    );
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, []);

  // Keyboard shortcut: Cmd+K to focus search
  useEffect(() => {
    function handleKeyDown(e: KeyboardEvent) {
      if ((e.metaKey || e.ctrlKey) && e.key === "k") {
        e.preventDefault();
        const input = document.querySelector<HTMLInputElement>(".search-input");
        input?.focus();
      }
      if (e.key === "Escape") {
        const input = document.querySelector<HTMLInputElement>(".search-input");
        input?.blur();
      }
    }
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, []);

  return (
    <div className="flex flex-col min-h-screen relative">
      {/* Top loading bar */}
      {isSearching && sourceCount < 14 && (
        <div className="top-loading-bar" aria-hidden="true">
          <div
            className="top-loading-bar-fill"
            style={{ width: `${Math.min((sourceCount / 14) * 100, 95)}%` }}
          />
        </div>
      )}

      {/* Grid background */}
      <div className="grid-lines" />

      {/* Header */}
      <header className="app-header relative z-10" role="banner">
        <div className="max-w-[1600px] mx-auto px-4 py-3 flex items-center justify-between gap-4">
          <div className="flex-shrink-0">
            <div className="logo">PROPVISION</div>
            <div className="logo-sub">AI INVESTMENT COMMAND CENTER</div>
          </div>

          {hasSearched && (
            <SearchBar onSearch={handleSearch} isSearching={isSearching && sourceCount < 14} />
          )}

          <div className="flex-shrink-0 flex items-center gap-3">
            {hasSearched && sourceCount > 0 && (
              <div className="source-counter" role="status" aria-live="polite">
                <div className="source-dot" aria-hidden="true" />
                <div className="source-counter-content">
                  <span>
                    {sourceCount < 14
                      ? `Analyzing ${sourceCount}/14 sources...`
                      : "14 sources analyzed"}
                  </span>
                  {sourceCount < 14 && currentSourceName && (
                    <span className="source-name">{currentSourceName}</span>
                  )}
                </div>
              </div>
            )}
            {hasSearched && sourceCount >= 14 && (
              <div className="header-actions">
                <button
                  className="action-btn action-btn-secondary"
                  onClick={handleNewAnalysis}
                  aria-label="New analysis"
                  title="Analyze another property"
                >
                  <Search size={14} />
                  <span className="hidden sm:inline">New Analysis</span>
                </button>
                <button
                  className="action-btn"
                  onClick={() => {}}
                  aria-label="Generate PDF report"
                  title="Generate PDF Report"
                >
                  <FileDown size={14} />
                  <span className="hidden sm:inline">PDF Report</span>
                </button>
                <button
                  className="action-btn action-btn-secondary"
                  onClick={() => {}}
                  aria-label="Export to CSV"
                  title="Export to CSV"
                >
                  <FileSpreadsheet size={14} />
                  <span className="hidden sm:inline">CSV</span>
                </button>
                <button
                  className="action-btn action-btn-secondary"
                  onClick={handleShare}
                  aria-label="Share analysis"
                  title="Share Analysis"
                >
                  {copied ? <Check size={14} /> : <Share2 size={14} />}
                  <span className="hidden sm:inline">{copied ? "Copied!" : "Share"}</span>
                </button>
              </div>
            )}
            <div className="hidden md:flex items-center gap-3">
              <div className="status-indicator" aria-label="API status: connected">
                <div className="status-dot" aria-hidden="true" />
                API
              </div>
              <div className="status-indicator" aria-label="Live data status: active">
                <div className="status-dot" aria-hidden="true" />
                LIVE
              </div>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 relative z-10" role="main">
        {!hasSearched ? (
          <div className="empty-state">
            {/* Floating data particles */}
            <div className="data-particles">
              <span className="data-particle">$425,000</span>
              <span className="data-particle">ROI 8.2%</span>
              <span className="data-particle">Cap Rate 6.1</span>
              <span className="data-particle">3bd / 2ba</span>
              <span className="data-particle">$2,450/mo</span>
              <span className="data-particle">Appreciation +4.3%</span>
              <span className="data-particle">Walk Score 82</span>
              <span className="data-particle">Days on Market 12</span>
            </div>

            {/* Scan line */}
            <div className="scan-line" />

            {/* Radar animation */}
            <div className="radar-container">
              <div className="radar-ring" />
              <div className="radar-ring" />
              <div className="radar-ring" />
              <div className="radar-ring" />
              <div className="radar-sweep" />
            </div>

            <div className="fade-up">
              <div className="empty-state-title">PROPVISION</div>
              <div className="logo-sub text-center mt-1">
                AI PROPERTY INVESTMENT COMMAND CENTER
              </div>
            </div>

            <p className="empty-state-sub fade-up">
              Enter any US property address to generate a comprehensive
              AI-powered investment analysis. Real-time data from 14+ sources
              including MLS, public records, and neural search intelligence.
            </p>

            {/* Property Type Selector */}
            <div className="property-type-selector fade-up" role="radiogroup" aria-label="Property type">
              {([
                { key: "condo" as const, label: "Condo", icon: <Building2 size={14} /> },
                { key: "multi-family" as const, label: "Multi-Family", icon: <Hotel size={14} /> },
                { key: "single-family" as const, label: "Single Family", icon: <HomeIcon size={14} /> },
              ]).map((pt) => (
                <button
                  key={pt.key}
                  role="radio"
                  aria-checked={propertyType === pt.key}
                  className={`property-type-btn ${propertyType === pt.key ? "property-type-btn-active" : ""}`}
                  onClick={() => setPropertyType(pt.key)}
                >
                  {pt.icon}
                  {pt.label}
                </button>
              ))}
            </div>

            <div className="fade-up" style={{ width: "100%", display: "flex", justifyContent: "center" }}>
              <SearchBar
                onSearch={handleSearch}
                isSearching={isSearching && sourceCount < 14}
                autoFocus
              />
            </div>

            {/* Live stats ticker */}
            <div className="stats-ticker fade-up">
              <div className="ticker-item">
                <span className="ticker-value">2.4M</span>
                <span className="ticker-label">Properties</span>
              </div>
              <div className="ticker-divider" />
              <div className="ticker-item">
                <span className="ticker-value cyan">14</span>
                <span className="ticker-label">Data Sources</span>
              </div>
              <div className="ticker-divider" />
              <div className="ticker-item">
                <span className="ticker-value">98%</span>
                <span className="ticker-label">Accuracy</span>
              </div>
              <div className="ticker-divider" />
              <div className="ticker-item">
                <span className="ticker-value cyan">&lt;3s</span>
                <span className="ticker-label">Analysis</span>
              </div>
            </div>

            <div className="feature-grid fade-up">
              <div className="feature-card">
                <div className="feature-card-icon-wrap">
                  <TrendingUp size={18} className="feature-card-icon" />
                </div>
                <span className="feature-card-label">Market Trends</span>
                <span className="feature-card-desc">Live pricing and appreciation data</span>
              </div>
              <div className="feature-card">
                <div className="feature-card-icon-wrap">
                  <Brain size={18} className="feature-card-icon" />
                </div>
                <span className="feature-card-label">AI Analysis</span>
                <span className="feature-card-desc">Neural-powered investment briefs</span>
              </div>
              <div className="feature-card">
                <div className="feature-card-icon-wrap">
                  <Shield size={18} className="feature-card-icon" />
                </div>
                <span className="feature-card-label">Risk Scoring</span>
                <span className="feature-card-desc">Multi-factor risk assessment</span>
              </div>
              <div className="feature-card">
                <div className="feature-card-icon-wrap">
                  <BarChart3 size={18} className="feature-card-icon" />
                </div>
                <span className="feature-card-label">Cash Flow</span>
                <span className="feature-card-desc">Rent estimates and projections</span>
              </div>
              <div className="feature-card">
                <div className="feature-card-icon-wrap">
                  <Zap size={18} className="feature-card-icon" />
                </div>
                <span className="feature-card-label">14+ Sources</span>
                <span className="feature-card-desc">MLS, records, and more</span>
              </div>
              <div className="feature-card">
                <div className="feature-card-icon-wrap">
                  <Globe size={18} className="feature-card-icon" />
                </div>
                <span className="feature-card-label">Live Intel</span>
                <span className="feature-card-desc">Real-time market intelligence</span>
              </div>
            </div>

            <div className="flex items-center gap-3 mt-2 fade-up">
              <span className="kbd">⌘K</span>
              <span className="text-xs text-zinc-600 font-mono">to search</span>
            </div>
          </div>
        ) : (
          <ErrorBoundary fallbackTitle="Dashboard failed to load">
          {/* Neural Search Initialization Overlay */}
          {isInitializing && (
            <div className="neural-init-overlay">
              <div className="neural-init-content">
                <div className="neural-init-rings">
                  <div className="neural-init-ring" />
                  <div className="neural-init-ring" />
                  <div className="neural-init-ring" />
                </div>
                <div className="neural-init-text">
                  <Loader2 size={14} className="inline animate-spin mr-2 text-accent" />
                  {currentSourceName}
                </div>
              </div>
            </div>
          )}
          {/* AI Badge & Timestamp Bar */}
          {sourceCount >= 14 && (
            <div className="analysis-meta-bar">
              <div className="ai-badge">
                <Sparkles size={12} />
                AI-Generated Analysis
              </div>
              <span className="analysis-timestamp">
                Analysis generated {analysisTimestamp}
              </span>
              <button
                className="how-it-works-btn"
                onClick={() => setShowHowItWorks(!showHowItWorks)}
                aria-expanded={showHowItWorks}
                aria-label="How it works"
              >
                <Info size={12} />
                How it works
              </button>
              {showHowItWorks && (
                <div className="how-it-works-tooltip">
                  <div className="how-it-works-title">Data Sources & Methodology</div>
                  <p>PropVision aggregates data from 14+ sources in real-time:</p>
                  <ul>
                    <li><strong>Valuation:</strong> MLS listings, public deed records, county assessor data</li>
                    <li><strong>Rental:</strong> RentCast API, Zillow Rental Index, lease comps</li>
                    <li><strong>Market Intel:</strong> Exa neural search, news feeds, permit filings</li>
                    <li><strong>Neighborhood:</strong> Census ACS, Walk Score, NYPD CompStat, GreatSchools</li>
                    <li><strong>AI Brief:</strong> Claude AI synthesizes all sources into actionable insights</li>
                  </ul>
                </div>
              )}
            </div>
          )}
          <div className="dashboard-grid" role="region" aria-label="Property analysis dashboard">
            <PropertyDetails
              data={mockProperty}
              visible={visiblePanels[0]}
              loaded={loadedPanels[0]}
            />
            <MapView
              property={mockProperty}
              comparables={mockComparables}
              visible={visiblePanels[1]}
              loaded={loadedPanels[1]}
            />
            <RentGauge
              data={mockRentEstimate}
              visible={visiblePanels[2]}
              loaded={loadedPanels[2]}
            />
            <MarketTrends
              data={mockMarketData}
              visible={visiblePanels[3]}
              loaded={loadedPanels[3]}
            />
            <Comparables
              data={mockComparables}
              visible={visiblePanels[4]}
              loaded={loadedPanels[4]}
            />
            <CompareProperties
              subject={mockProperty}
              comp={mockComparables[0]}
              visible={visiblePanels[5]}
              loaded={loadedPanels[5]}
            />
            <NeighborhoodStats
              data={mockNeighborhood}
              visible={visiblePanels[6]}
              loaded={loadedPanels[6]}
            />
            <Suspense fallback={<PanelCard title="CASH FLOW CALCULATOR" visible={visiblePanels[7]} loaded={false}><ShimmerLoader lines={6} /></PanelCard>}>
              <CashFlowCalculator
                visible={visiblePanels[7]}
                loaded={loadedPanels[7]}
                propertyValue={mockProperty.estimatedValue}
                monthlyRent={mockRentEstimate.mid}
              />
            </Suspense>
            <Suspense fallback={<PanelCard title="RISK ASSESSMENT" visible={visiblePanels[8]} loaded={false}><ShimmerLoader lines={6} /></PanelCard>}>
              <RiskScore
                visible={visiblePanels[8]}
                loaded={loadedPanels[8]}
              />
            </Suspense>
            <Suspense fallback={<PanelCard title="AI INTELLIGENCE FEED" visible={visiblePanels[9]} loaded={false}><ShimmerLoader lines={6} /></PanelCard>}>
              <IntelligenceFeed
                data={mockIntelItems}
                visible={visiblePanels[9]}
                loaded={loadedPanels[9]}
              />
            </Suspense>
            <Suspense fallback={<PanelCard title="AI INVESTMENT BRIEF" visible={visiblePanels[10]} loaded={false}><ShimmerLoader lines={6} /></PanelCard>}>
              <InvestmentBrief
                content={mockInvestmentBrief}
                visible={visiblePanels[10]}
                loaded={loadedPanels[10]}
              />
            </Suspense>
          </div>
          </ErrorBoundary>
        )}
      </main>

      {/* Footer */}
      <footer className="app-footer relative z-10" role="contentinfo">
        <div className="footer-inner">
          <div className="footer-brand">
            <span className="footer-logo">PROPVISION</span>
            <span className="footer-tagline">AI Investment Intelligence</span>
          </div>
          <div className="footer-powered">
            <span className="footer-label">POWERED BY</span>
            <div className="footer-sources">
              <span className="footer-source">Exa Neural Search</span>
              <span className="footer-dot" />
              <span className="footer-source">Claude AI</span>
              <span className="footer-dot" />
              <span className="footer-source">RentCast</span>
              <span className="footer-dot" />
              <span className="footer-source">Walk Score</span>
            </div>
          </div>
          <div className="footer-meta">
            <span className="footer-version">v2.4.0</span>
            <span className="footer-separator">|</span>
            <span className="footer-status">
              <span className="footer-status-dot" />
              All Systems Operational
            </span>
          </div>
        </div>
        <div className="footer-gradient" />
      </footer>
    </div>
  );
}
