"use client";

import { useState, useCallback, useEffect } from "react";
import {
  TrendingUp,
  Brain,
  Shield,
  BarChart3,
  Zap,
  Globe,
  FileDown,
  Share2,
  Check,
} from "lucide-react";
import { SearchBar } from "@/components/SearchBar";
import { PropertyDetails } from "@/components/PropertyDetails";
import { MapView } from "@/components/MapView";
import { RentGauge } from "@/components/RentGauge";
import { MarketTrends } from "@/components/MarketTrends";
import { Comparables } from "@/components/Comparables";
import { NeighborhoodStats } from "@/components/NeighborhoodStats";
import { IntelligenceFeed } from "@/components/IntelligenceFeed";
import { InvestmentBrief } from "@/components/InvestmentBrief";
import { CashFlowCalculator } from "@/components/CashFlowCalculator";
import { RiskScore } from "@/components/RiskScore";
import { useStaggeredLoad } from "@/hooks/useStaggeredLoad";
import {
  mockProperty,
  mockComparables,
  mockRentEstimate,
  mockMarketData,
  mockNeighborhood,
  mockIntelItems,
  mockInvestmentBrief,
} from "@/lib/mockData";

export default function Home() {
  const [hasSearched, setHasSearched] = useState(false);
  const { visiblePanels, loadedPanels, sourceCount, currentSourceName, isSearching, triggerLoad } =
    useStaggeredLoad(10);

  const [copied, setCopied] = useState(false);

  const handleSearch = useCallback(
    (_address: string) => {
      setHasSearched(true);
      triggerLoad();
    },
    [triggerLoad]
  );

  const handleShare = useCallback(() => {
    navigator.clipboard.writeText(
      `PropVision Analysis: 350 Fifth Avenue, New York, NY 10118\n\nEstimated Value: $1,275,000\nRent Estimate: $4,500/mo\nCap Rate: 4.24%\nRisk Rating: LOW-MODERATE\n\nGenerated by PropVision AI — propvision.ai`
    );
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, []);

  // Keyboard shortcut: Cmd+K to focus search
  useEffect(() => {
    function handleKeyDown(e: KeyboardEvent) {
      if ((e.metaKey || e.ctrlKey) && e.key === "k") {
        e.preventDefault();
        const input = document.querySelector<HTMLInputElement>(".search-input");
        input?.focus();
      }
      if (e.key === "Escape") {
        const input = document.querySelector<HTMLInputElement>(".search-input");
        input?.blur();
      }
    }
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, []);

  return (
    <div className="flex flex-col min-h-screen relative">
      {/* Grid background */}
      <div className="grid-lines" />

      {/* Header */}
      <header className="app-header relative z-10" role="banner">
        <div className="max-w-[1600px] mx-auto px-4 py-3 flex items-center justify-between gap-4">
          <div className="flex-shrink-0">
            <div className="logo">PROPVISION</div>
            <div className="logo-sub">AI INVESTMENT COMMAND CENTER</div>
          </div>

          {hasSearched && (
            <SearchBar onSearch={handleSearch} isSearching={isSearching && sourceCount < 14} />
          )}

          <div className="flex-shrink-0 flex items-center gap-3">
            {hasSearched && sourceCount > 0 && (
              <div className="source-counter" role="status" aria-live="polite">
                <div className="source-dot" aria-hidden="true" />
                <div className="source-counter-content">
                  <span>
                    {sourceCount < 14
                      ? `Analyzing ${sourceCount}/14 sources...`
                      : "14 sources analyzed"}
                  </span>
                  {sourceCount < 14 && currentSourceName && (
                    <span className="source-name">{currentSourceName}</span>
                  )}
                </div>
              </div>
            )}
            {hasSearched && sourceCount >= 14 && (
              <div className="flex items-center gap-2">
                <button
                  className="action-btn"
                  onClick={() => {}}
                  aria-label="Generate PDF report"
                  title="Generate PDF Report"
                >
                  <FileDown size={14} />
                  <span className="hidden sm:inline">PDF Report</span>
                </button>
                <button
                  className="action-btn action-btn-secondary"
                  onClick={handleShare}
                  aria-label="Share analysis"
                  title="Share Analysis"
                >
                  {copied ? <Check size={14} /> : <Share2 size={14} />}
                  <span className="hidden sm:inline">{copied ? "Copied!" : "Share"}</span>
                </button>
              </div>
            )}
            <div className="hidden md:flex items-center gap-3">
              <div className="status-indicator" aria-label="API status: connected">
                <div className="status-dot" aria-hidden="true" />
                API
              </div>
              <div className="status-indicator" aria-label="Live data status: active">
                <div className="status-dot" aria-hidden="true" />
                LIVE
              </div>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 relative z-10" role="main">
        {!hasSearched ? (
          <div className="empty-state">
            {/* Floating data particles */}
            <div className="data-particles">
              <span className="data-particle">$425,000</span>
              <span className="data-particle">ROI 8.2%</span>
              <span className="data-particle">Cap Rate 6.1</span>
              <span className="data-particle">3bd / 2ba</span>
              <span className="data-particle">$2,450/mo</span>
              <span className="data-particle">Appreciation +4.3%</span>
              <span className="data-particle">Walk Score 82</span>
              <span className="data-particle">Days on Market 12</span>
            </div>

            {/* Scan line */}
            <div className="scan-line" />

            {/* Radar animation */}
            <div className="radar-container">
              <div className="radar-ring" />
              <div className="radar-ring" />
              <div className="radar-ring" />
              <div className="radar-ring" />
              <div className="radar-sweep" />
            </div>

            <div className="fade-up">
              <div className="empty-state-title">PROPVISION</div>
              <div className="logo-sub text-center mt-1">
                AI PROPERTY INVESTMENT COMMAND CENTER
              </div>
            </div>

            <p className="empty-state-sub fade-up">
              Enter any US property address to generate a comprehensive
              AI-powered investment analysis. Real-time data from 14+ sources
              including MLS, public records, and neural search intelligence.
            </p>

            <div className="fade-up" style={{ width: "100%", display: "flex", justifyContent: "center" }}>
              <SearchBar
                onSearch={handleSearch}
                isSearching={isSearching && sourceCount < 14}
                autoFocus
              />
            </div>

            {/* Live stats ticker */}
            <div className="stats-ticker fade-up">
              <div className="ticker-item">
                <span className="ticker-value">2.4M</span>
                <span className="ticker-label">Properties</span>
              </div>
              <div className="ticker-divider" />
              <div className="ticker-item">
                <span className="ticker-value cyan">14</span>
                <span className="ticker-label">Data Sources</span>
              </div>
              <div className="ticker-divider" />
              <div className="ticker-item">
                <span className="ticker-value">98%</span>
                <span className="ticker-label">Accuracy</span>
              </div>
              <div className="ticker-divider" />
              <div className="ticker-item">
                <span className="ticker-value cyan">&lt;3s</span>
                <span className="ticker-label">Analysis</span>
              </div>
            </div>

            <div className="feature-grid fade-up">
              <div className="feature-card">
                <div className="feature-card-icon-wrap">
                  <TrendingUp size={18} className="feature-card-icon" />
                </div>
                <span className="feature-card-label">Market Trends</span>
                <span className="feature-card-desc">Live pricing and appreciation data</span>
              </div>
              <div className="feature-card">
                <div className="feature-card-icon-wrap">
                  <Brain size={18} className="feature-card-icon" />
                </div>
                <span className="feature-card-label">AI Analysis</span>
                <span className="feature-card-desc">Neural-powered investment briefs</span>
              </div>
              <div className="feature-card">
                <div className="feature-card-icon-wrap">
                  <Shield size={18} className="feature-card-icon" />
                </div>
                <span className="feature-card-label">Risk Scoring</span>
                <span className="feature-card-desc">Multi-factor risk assessment</span>
              </div>
              <div className="feature-card">
                <div className="feature-card-icon-wrap">
                  <BarChart3 size={18} className="feature-card-icon" />
                </div>
                <span className="feature-card-label">Cash Flow</span>
                <span className="feature-card-desc">Rent estimates and projections</span>
              </div>
              <div className="feature-card">
                <div className="feature-card-icon-wrap">
                  <Zap size={18} className="feature-card-icon" />
                </div>
                <span className="feature-card-label">14+ Sources</span>
                <span className="feature-card-desc">MLS, records, and more</span>
              </div>
              <div className="feature-card">
                <div className="feature-card-icon-wrap">
                  <Globe size={18} className="feature-card-icon" />
                </div>
                <span className="feature-card-label">Live Intel</span>
                <span className="feature-card-desc">Real-time market intelligence</span>
              </div>
            </div>

            <div className="flex items-center gap-3 mt-2 fade-up">
              <span className="kbd">⌘K</span>
              <span className="text-xs text-zinc-600 font-mono">to search</span>
            </div>
          </div>
        ) : (
          <div className="dashboard-grid" role="region" aria-label="Property analysis dashboard">
            <PropertyDetails
              data={mockProperty}
              visible={visiblePanels[0]}
              loaded={loadedPanels[0]}
            />
            <MapView
              property={mockProperty}
              comparables={mockComparables}
              visible={visiblePanels[1]}
              loaded={loadedPanels[1]}
            />
            <RentGauge
              data={mockRentEstimate}
              visible={visiblePanels[2]}
              loaded={loadedPanels[2]}
            />
            <MarketTrends
              data={mockMarketData}
              visible={visiblePanels[3]}
              loaded={loadedPanels[3]}
            />
            <Comparables
              data={mockComparables}
              visible={visiblePanels[4]}
              loaded={loadedPanels[4]}
            />
            <NeighborhoodStats
              data={mockNeighborhood}
              visible={visiblePanels[5]}
              loaded={loadedPanels[5]}
            />
            <CashFlowCalculator
              visible={visiblePanels[6]}
              loaded={loadedPanels[6]}
              propertyValue={mockProperty.estimatedValue}
              monthlyRent={mockRentEstimate.mid}
            />
            <RiskScore
              visible={visiblePanels[7]}
              loaded={loadedPanels[7]}
            />
            <IntelligenceFeed
              data={mockIntelItems}
              visible={visiblePanels[8]}
              loaded={loadedPanels[8]}
            />
            <InvestmentBrief
              content={mockInvestmentBrief}
              visible={visiblePanels[9]}
              loaded={loadedPanels[9]}
            />
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="app-footer relative z-10">
        Powered by <span>Exa Neural Search</span> &bull;{" "}
        <span>Claude AI</span> &bull; <span>RentCast</span>
      </footer>
    </div>
  );
}
